[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.12.3",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
]
